create table Country
(
    ID          int identity
        constraint Country_pk
            primary key nonclustered,
    Name        varchar(255) not null,
    Language    varchar(255),
    CountryCode varchar(255) not null
)
go

create unique index Country_ID_uindex
    on Country (ID)
go

create unique index Country_Name_uindex
    on Country (Name)
go

create unique index Country_CountryCode_uindex
    on Country (CountryCode)
go

INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (6, N'Afghanistan', N'NL', N'AF');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (7, N'Åland (Åland Islands)', N'NL', N'AX');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (8, N'Albanië', N'NL', N'AL');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (9, N'Algerije', N'NL', N'DZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (10, N'Amerikaanse Maagdeneilanden', N'NL', N'VI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (11, N'Amerikaans-Samoa', N'NL', N'AS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (12, N'Andorra', N'NL', N'AD');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (13, N'Angola', N'NL', N'AO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (14, N'Anguilla', N'NL', N'AI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (15, N'Antarctica', N'NL', N'AQ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (16, N'Antigua en Barbuda', N'NL', N'AG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (17, N'Argentinië', N'NL', N'AR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (18, N'Armenië', N'NL', N'AM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (19, N'Aruba', N'NL', N'AW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (20, N'Australië', N'NL', N'AU');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (21, N'Azerbeidzjan', N'NL', N'AZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (22, N'Bahamas', N'NL', N'BS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (23, N'Bahrein', N'NL', N'BH');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (24, N'Bangladesh', N'NL', N'BD');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (25, N'Barbados', N'NL', N'BB');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (26, N'België', N'NL', N'BE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (27, N'Belize', N'NL', N'BZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (28, N'Benin', N'NL', N'BJ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (29, N'Bermuda', N'NL', N'BM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (30, N'Bhutan', N'NL', N'BT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (31, N'Bolivia', N'NL', N'BO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (32, N'Bonaire, Sint Eustatius en Saba', N'NL', N'BQ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (33, N'Bosnië en Herzegovina', N'NL', N'BA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (34, N'Botswana', N'NL', N'BW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (35, N'Bouveteiland', N'NL', N'BV');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (36, N'Brazilië', N'NL', N'BR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (37, N'Britse Maagdeneilanden', N'NL', N'VG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (38, N'Brits Indische Oceaanterritorium', N'NL', N'IO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (39, N'Brunei', N'NL', N'BN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (40, N'Bulgarije', N'NL', N'BG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (41, N'Burkina Faso', N'NL', N'BF');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (42, N'Burundi', N'NL', N'BI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (43, N'Cambodja', N'NL', N'KH');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (44, N'Canada', N'NL', N'CA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (45, N'Centraal-Afrikaanse Republiek', N'NL', N'CF');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (46, N'Chili', N'NL', N'CL');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (47, N'China', N'NL', N'CN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (48, N'Christmaseiland', N'NL', N'CX');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (49, N'Cocoseilanden', N'NL', N'CC');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (50, N'Colombia', N'NL', N'CO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (51, N'Comoren', N'NL', N'KM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (52, N'Congo-Brazzaville', N'NL', N'CG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (53, N'Congo-Kinshasa', N'NL', N'CD');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (54, N'Cookeilanden', N'NL', N'CK');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (55, N'Costa Rica', N'NL', N'CR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (56, N'Cuba', N'NL', N'CU');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (57, N'Curacao', N'NL', N'CW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (58, N'Cyprus', N'NL', N'CY');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (59, N'Denemarken', N'NL', N'DK');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (60, N'Djibouti', N'NL', N'DJ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (61, N'Dominica', N'NL', N'DM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (62, N'Dominicaanse Republiek', N'NL', N'DO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (63, N'Duitsland', N'NL', N'DE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (64, N'Ecuador', N'NL', N'EC');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (65, N'Egypte', N'NL', N'EG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (66, N'El Salvador', N'NL', N'SV');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (67, N'Equatoriaal-Guinea', N'NL', N'GQ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (68, N'Eritrea', N'NL', N'ER');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (69, N'Estland', N'NL', N'EE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (70, N'Ethiopië', N'NL', N'ET');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (71, N'Faeröer', N'NL', N'FO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (72, N'Falklandeilanden', N'NL', N'FK');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (73, N'Fiji', N'NL', N'FJ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (74, N'Filipijnen', N'NL', N'PH');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (75, N'Finland', N'NL', N'FI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (76, N'Frankrijk', N'NL', N'FR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (77, N'Franse Zuidelijke en Antarctische Gebieden', N'NL', N'TF');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (78, N'Frans-Guyana', N'NL', N'GF');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (79, N'Frans-Polynesië', N'NL', N'PF');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (80, N'Gabon', N'NL', N'GA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (81, N'Gambia', N'NL', N'GM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (82, N'Georgië', N'NL', N'GE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (83, N'Ghana', N'NL', N'GH');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (84, N'Gibraltar', N'NL', N'GI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (85, N'Grenada', N'NL', N'GD');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (86, N'Griekenland', N'NL', N'GR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (87, N'Groenland', N'NL', N'GL');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (88, N'Guadeloupe', N'NL', N'GP');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (89, N'Guam', N'NL', N'GU');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (90, N'Guatemala', N'NL', N'GT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (91, N'Guernsey', N'NL', N'GG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (92, N'Guinee', N'NL', N'GN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (93, N'Guinee-Bissau', N'NL', N'GW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (94, N'Guyana', N'NL', N'GY');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (95, N'Haïti', N'NL', N'HT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (96, N'Heard en McDonaldeilanden', N'NL', N'HM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (97, N'Honduras', N'NL', N'HN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (98, N'Hongarije', N'NL', N'HU');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (99, N'Hongkong', N'NL', N'HK');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (100, N'Ierland', N'NL', N'IE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (101, N'IJsland', N'NL', N'IS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (102, N'India', N'NL', N'IN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (103, N'Indonesië', N'NL', N'ID');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (104, N'Irak', N'NL', N'IQ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (105, N'Iran', N'NL', N'IR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (106, N'Israel', N'NL', N'IL');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (107, N'Italië', N'NL', N'IT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (108, N'Ivoorkust', N'NL', N'CI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (109, N'Jamaica', N'NL', N'JM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (110, N'Japan', N'NL', N'JP');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (111, N'Jemen', N'NL', N'YE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (112, N'Jersey', N'NL', N'JE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (113, N'Jordanië', N'NL', N'JO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (114, N'Kaaimaneilanden', N'NL', N'KY');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (115, N'Kaapverdië', N'NL', N'CV');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (116, N'Kameroen', N'NL', N'CM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (117, N'Kazachstan', N'NL', N'KZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (118, N'Kenia', N'NL', N'KE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (119, N'Kirgizië', N'NL', N'KG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (120, N'Kiribati', N'NL', N'KI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (121, N'Kleine Pacifische eilanden van de V.S.', N'NL', N'UM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (122, N'Koeweit', N'NL', N'KW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (123, N'Kroatië', N'NL', N'HR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (124, N'Laos', N'NL', N'LA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (125, N'Lesotho', N'NL', N'LS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (126, N'Letland', N'NL', N'LV');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (127, N'Libanon', N'NL', N'LB');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (128, N'Liberia', N'NL', N'LR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (129, N'Libië', N'NL', N'LY');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (130, N'Liechtenstein', N'NL', N'LI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (131, N'Litouwen', N'NL', N'LT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (132, N'Luxemburg', N'NL', N'LU');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (133, N'Macau', N'NL', N'MO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (134, N'Macedonië', N'NL', N'MK');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (135, N'Madagaskar', N'NL', N'MG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (136, N'Malawi', N'NL', N'MW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (137, N'Maldiven', N'NL', N'MV');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (138, N'Maleisië', N'NL', N'MY');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (139, N'Mali', N'NL', N'ML');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (140, N'Malta', N'NL', N'MT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (141, N'Man', N'NL', N'IM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (142, N'Marokko', N'NL', N'MA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (143, N'Marshalleilanden', N'NL', N'MH');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (144, N'Martinique', N'NL', N'MQ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (145, N'Mauritanië', N'NL', N'MR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (146, N'Mauritius', N'NL', N'MU');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (147, N'Mayotte', N'NL', N'YT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (148, N'Mexico', N'NL', N'MX');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (149, N'Micronesia', N'NL', N'FM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (150, N'Moldavië', N'NL', N'MD');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (151, N'Monaco', N'NL', N'MC');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (152, N'Mongolië', N'NL', N'MN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (153, N'Montenegro', N'NL', N'ME');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (154, N'Montserrat', N'NL', N'MS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (155, N'Mozambique', N'NL', N'MZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (156, N'Myanmar', N'NL', N'MM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (157, N'Namibië', N'NL', N'NA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (158, N'Nauru', N'NL', N'NR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (159, N'Nederland', N'NL', N'NL');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (160, N'Nepal', N'NL', N'NP');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (161, N'Nicaragua', N'NL', N'NI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (162, N'Nieuw-Caledonië', N'NL', N'NC');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (163, N'Nieuw-Zeeland', N'NL', N'NZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (164, N'Niger', N'NL', N'NE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (165, N'Nigeria', N'NL', N'NG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (166, N'Niue', N'NL', N'NU');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (167, N'Noordelijke Marianen', N'NL', N'MP');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (168, N'Noord-Korea', N'NL', N'KP');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (169, N'Noorwegen', N'NL', N'NO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (170, N'Norfolk', N'NL', N'NF');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (171, N'Oeganda', N'NL', N'UG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (172, N'Oekraine', N'NL', N'UA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (173, N'Oezbekistan', N'NL', N'UZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (174, N'Oman', N'NL', N'OM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (175, N'Oostenrijk', N'NL', N'AT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (176, N'Oost-Timor', N'NL', N'TL');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (177, N'Pakistan', N'NL', N'PK');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (178, N'Palau', N'NL', N'PW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (179, N'Palestina', N'NL', N'PS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (180, N'Panama', N'NL', N'PA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (181, N'Papoea-Nieuw-Guinea', N'NL', N'PG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (182, N'Paraguay', N'NL', N'PY');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (183, N'Peru', N'NL', N'PE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (184, N'Pitcairneilanden', N'NL', N'PN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (185, N'Polen', N'NL', N'PL');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (186, N'Portugal', N'NL', N'PT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (187, N'Puerto Rico', N'NL', N'PR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (188, N'Qatar', N'NL', N'QA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (189, N'Réunion', N'NL', N'RE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (190, N'Roemenië', N'NL', N'RO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (191, N'Rusland', N'NL', N'RU');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (192, N'Rwanda', N'NL', N'RW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (193, N'Saint-Barthélemy', N'NL', N'BL');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (194, N'Saint Kitts en Nevis', N'NL', N'KN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (195, N'Saint Lucia', N'NL', N'LC');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (196, N'Saint-Pierre en Miquelon', N'NL', N'PM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (197, N'Saint Vincent en de Grenadines', N'NL', N'VC');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (198, N'Salomonseilanden', N'NL', N'SB');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (199, N'Samoa', N'NL', N'WS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (200, N'San Marino', N'NL', N'SM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (201, N'Saoedi-Arabië', N'NL', N'SA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (202, N'Sao Tom&eacute; en Principe', N'NL', N'ST');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (203, N'Senegal', N'NL', N'SN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (204, N'Servië', N'NL', N'RS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (205, N'Seychellen', N'NL', N'SC');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (206, N'Sierra Leone', N'NL', N'SL');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (207, N'Singapore', N'NL', N'SG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (208, N'Sint-Helena, Ascension en Tristan da Cunha', N'NL', N'SH');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (209, N'Sint-Maarten', N'NL', N'MF');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (210, N'Sint Maarten', N'NL', N'SX');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (211, N'Slovenië', N'NL', N'SI');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (212, N'Slowakije', N'NL', N'SK');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (213, N'Soedan', N'NL', N'SD');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (214, N'Somalië', N'NL', N'SO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (215, N'Spanje', N'NL', N'ES');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (216, N'Spitsbergen en Jan Mayen', N'NL', N'SJ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (217, N'Sri Lanka', N'NL', N'LK');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (218, N'Suriname', N'NL', N'SR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (219, N'Swaziland', N'NL', N'SZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (220, N'Syrië', N'NL', N'SY');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (221, N'Tadzjikistan', N'NL', N'TJ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (222, N'Taiwan', N'NL', N'TW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (223, N'Tanzania', N'NL', N'TZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (224, N'Thailand', N'NL', N'TH');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (225, N'Togo', N'NL', N'TG');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (226, N'Tokelau', N'NL', N'TK');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (227, N'Tonga', N'NL', N'TO');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (228, N'Trinidad en Tobago', N'NL', N'TT');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (229, N'Tsjaad', N'NL', N'TD');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (230, N'Tsjechië', N'NL', N'CZ');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (231, N'Tunesië', N'NL', N'TN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (232, N'Turkije', N'NL', N'TR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (233, N'Turkmenistan', N'NL', N'TM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (234, N'Turks- en Caicoseilanden', N'NL', N'TC');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (235, N'Tuvalu', N'NL', N'TV');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (236, N'Uruguay', N'NL', N'UY');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (237, N'Vanuatu', N'NL', N'VU');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (238, N'Vaticaanstad', N'NL', N'VA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (239, N'Venezuela', N'NL', N'VE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (240, N'Verenigde Arabische Emiraten', N'NL', N'AE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (241, N'Verenigde Staten', N'NL', N'US');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (242, N'Verenigd Koninkrijk', N'NL', N'GB');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (243, N'Vietnam', N'NL', N'VN');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (244, N'Wallis en Futuna', N'NL', N'WF');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (245, N'Westelijke Sahara', N'NL', N'EH');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (246, N'Wit-Rusland', N'NL', N'BY');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (247, N'Zambia', N'NL', N'ZM');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (248, N'Zimbabwe', N'NL', N'ZW');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (249, N'Zuid-Afrika', N'NL', N'ZA');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (250, N'Zuid-Georgia en de Zuidelijke Sandwicheilanden', N'NL', N'GS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (251, N'Zuid-Korea', N'NL', N'KR');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (252, N'Zuid-Soedan', N'NL', N'SS');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (253, N'Zweden', N'NL', N'SE');
INSERT INTO Country (ID, Name, Language, CountryCode) VALUES (254, N'Zwitserland', N'NL', N'CH');